# Generated by Django 2.0.2 on 2018-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('file_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('URL', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('word', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=2000)),
            ],
        ),
    ]
