# Generated by Django 2.0.2 on 2018-03-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverted_index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('file_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('URL', models.CharField(max_length=2000)),
            ],
        ),
    ]
